// sign up user1
POST http://localhost:3000/api/auth/signup
content-type: application/json

{
    "uname": "user1",
    "pwd": "abCD1234!@"
}
###

// sign up user2
POST http://localhost:3000/api/auth/signup
content-type: application/json

{
    "uname": "user5",
    "pwd": "abCD1234!@",
    "emaddr": "user5@mail.com"
}
###


// sign in user1
POST http://localhost:3000/api/auth/signin
content-type: application/json

{
    "uname": "user5",
    "pwd": "abCD1234!@"
}
###

// me
GET http://localhost:3000/api/auth/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXIyIiwiaWF0IjoxNTc1NTk2Njc4LCJleHAiOjE1NzU2MDAyNzh9.sX9tDHVQT8k1MlzTYIX8QnNALr-Ou1NNZBN_xnBCIuo
###

// sign in user2
POST http://localhost:3000/api/auth/signin
content-type: application/json

{
    "uname": "user2",
    "pwd": "abCD1234!@"
}
###
